### ISSUE TITLE
Add support for generating fixtures

### ISSUE THREAD

**Issue by ninapavlich** [domasx2/sequelize-fixtures#106]
Forgive me if this exists already somewhere else, but what is the recommended method for generating JSON from the database that can be later imported through this tool?

If it doesn't exist already, I think it would be helpful to provide a command that is the inverse of the loadFile function, perhaps taking an array of models to include.

**Comment by matmar10** [comment]
This is likely out of scope for this project, but it would be interesting of we added a small adaptor logic or CLI script that could use a peer dependency like https://www.npmjs.com/package/faker 

Will close this but if you decide to work on support for integrating something like faker please re-open.
