### ISSUE TITLE
Missing release notes for 1.2

### ISSUE THREAD

**Issue by hugodes** [domasx2/sequelize-fixtures#119]
Hi,

There is no release info for v1.2:

https://github.com/domasx2/sequelize-fixtures/releases

Cheers,

**Comment by matmar10** [comment]
@domasx2 Looks like you manually cut a release?

FYI you can run 

```
npm run release -- [severity]
```

This is already set up in the project. It will automatically take care of all steps including github release notes. Reduces a lot of boilerplate steps and makes releasing much smoother.

Take a peak at https://www.npmjs.com/package/release-it

**Comment by matmar10** [comment]
Added. FYI @domasx2 if you still want to release manually you can run `npm run release` and follow the prompts only use it to create github release without any other steps :-)

**Comment by hugodes** [comment]
Thanks a lot !

**Comment by domasx2** [comment]
wasnt aware of this, cool, thanks :)
