### ISSUE TITLE
CI build status not appearing in Pull Request review on github

### ISSUE THREAD

**Issue by matmar10** [domasx2/sequelize-fixtures#122]
# Steps to Reproduce

- Cut a branch
- Make a breaking change (one that breaks test suite)
- Open a PR

# Expected Behavior

Pull request shows build status as failed due to Travis CI failing

# Actual Behavior 

No Travis CI build status displayed

**Comment by matmar10** [comment]
@domasx2  Any idea about this? I suspect it's some configuration setting for the repo. I don't have access to investigate or change project settings. Can you take a peak? 

Raising this because I accidentally merged a PR with breaking build change since status was not displayed in PR review.

**Comment by domasx2** [comment]
Hi, sure, will take a look when I have a moment

**Comment by domasx2** [comment]
I disabled/ reenabled this proejct on Travis and seems it started reporting status again.
Not sure what the cause was though... Will consider switching to github actions if I find some time

**Comment by domasx2** [comment]
closing, seems to be fine now
