### ISSUE TITLE
Does it support other associations?

### ISSUE THREAD

**Issue by JuSKT** [domasx2/sequelize-fixtures#26]
Hey,

Thanks for your work.

Does your library support other associations than the two ones of your readme?

See : http://sequelize.readthedocs.org/en/latest/api/associations/

Thanks.

**Comment by rodrigogoncalves** [comment]
Apparently not. Look at: https://github.com/domasx2/sequelize-fixtures/blob/master/lib/loader.js#L140

I am having a hard time trying to figure out how to load associations using this library.

**Comment by domasx2** [comment]
Hi,
Which association type are you missing specifically?

**Comment by JuSKT** [comment]
Hi,

Thanks for your responses.

@domasx2 I have some belongsToMany

**Comment by grabbou** [comment]
Yep, 2x many to many is deprecated now.

**Comment by domasx2** [comment]
added basic support for Belongs2Many.
what's missing is support for setting extra values to join table

**Comment by grabbou** [comment]
Finally! Thanks.
