### ISSUE TITLE
dump fixtures

### ISSUE THREAD

**Issue by Proxiweb** [domasx2/sequelize-fixtures#27]
Hello,

Thanks for this lib, very useful. Is there any plan for a dump fixture feature ?

**Comment by domasx2** [comment]
Hi, currently no plan, sorry. Dumping is likely a more complicated affair than loading. I'm currently not using this lib myself, so have little motivation to spend significant time on it. But pull requests are very welcome

**Comment by aleccool213** [comment]
@Proxiweb [This](https://github.com/boundstate/sequelize-test-setup) might be what you are looking for.

**Comment by matmar10** [comment]
Closing since old. @Proxiweb advise if lib mentioned by @aleccool213 works for you, otherwise feel free to reopen and, of course, contributions welcome :-)
