### ISSUE TITLE
Insert fails when select succeeds even with no unique constraint

### ISSUE THREAD

**Issue by nford** [domasx2/sequelize-fixtures#28]
I can understand if a duplicate record is not inserted when there is a unique constraint, but when I try to load fixtures with two identical records (an accident) the second is not inserted though as far as I can tell there is no reason it shouldn't be. Bug or feature?

v.0.4.0

**Comment by domasx2** [comment]
Hi! It's a feature. "Duplicate records are not insertd." it says, with a glorious typo, at the top of readme :)

**Comment by nford** [comment]
May I ask the rationale behind this? Is that not the purpose of a unique constraint?

**Comment by domasx2** [comment]
My original use case for this library was to load data for automated tests. Each test case had list of fixtures it depends upon, and these fixtures ocasionally contained some identical data. There was no requirement for the records to be unique in the business logic. I didn't want duplicate records while running tets and this is my solution.

I'm sure there exist valid use cases for identical records and it shouldn't bee too hard to make dupe check optional if someone has a use case for it
