### ISSUE TITLE
Models not building because they are undefined

### ISSUE THREAD

**Issue by ajfisher** [domasx2/sequelize-fixtures#3]
I'm trying to load a fixture into a sequelize object. It's very simple, a User model with a bunch of very basic string attributes. I'm not doing any associations or anything wacky there, simply trying to load one user at this point.

So my fixture looks like:

``` javascript

[{
  "model": "User",
  "data": {
    "firstname": "AJ",
    "surname": "Fisher"
  }
}]

```

When I go to load this fixture I'm getting a "cannot read "firstname" of Undefined" error. This is being thrown on Line 75 of loader.js which is this:

```
var assoc = Model.associations[key], val = data[key];
```

Tracing this through the debugger I can see why the error is happening which is that the Model at this point is just a function definition and is not a real "User" object, thus there's no associations and the key (firstname in this case) can't be found.

I can see that the model definition has been loaded as the function definition is correct.

I am probably missing something but I'd have thought that Model would have had to be instantiated in order to create a new object of that class before you can start manipulating the associations and then later the attributes and building it.

Nowhere in the code for loader.js can I see this happening so I'm trying to work out where this happens?

Any help would be appreciated as I'm trying to get one basic example working before then generating a decent sized fixture to load in.

**Comment by oliverbenns** [comment]
I had a similar issue recently that I spent way too much time on. This is due to the way babel exports work. In short, I had to revert to `module.exports` as opposed to `export default` for my fixtures.
