### ISSUE TITLE
Save on Sequelize 1.7.10

### ISSUE THREAD

**Issue by yagop** [domasx2/sequelize-fixtures#34]
I am using Sequelize 1.7.10, seems on that version if `Model.build()` second param is called with an Object it does an UPDATE even if there is no data on Database. I fixed changing line [17 of loader.js](https://github.com/domasx2/sequelize-fixtures/blob/master/lib/loader.js#L16). Also happens with 1.7.0.

```js
Loader.prototype.loadFixture = function(fixture, models) {
    var buildOptions = fixture.buildOptions,
        saveOptions = fixture.saveOptions || {},
```

Could be changed?

**Comment by domasx2** [comment]
done
