### ISSUE TITLE
handle json fields correctly

### ISSUE THREAD

**Issue by domasx2** [domasx2/sequelize-fixtures#37]

**Comment by domasx2** [comment]
On testing it seems that sequelize handles json fields correctly on postgres without any changes. Why are people having a problem then? Maybe using JSON sequelize datatype with mysql/sqlite

**Comment by domasx2** [comment]
if anyone has a problem with JSON, please let me know

**Comment by zxqfox** [comment]
Have troubles with sqlite

**Comment by domasx2** [comment]
i think sqlite does not support json fields, its postgres only

**Comment by zxqfox** [comment]
Well, yes, but this exception comes when I trying to load something to json field. Like it trying to retrieve what it stores and where statement becomes unreadable for sqlite: 
```
     SequelizeDatabaseError: SQLITE_ERROR: unrecognized token: "#"
      at [object Object].Query.formatError (node_modules/sequelize/lib/dialects/sqlite/query.js:242:14)
      at node_modules/sequelize/lib/dialects/sqlite/query.js:47:29
      at replacement (node_modules/sqlite3/lib/trace.js:20:31)
      at Statement.errBack (node_modules/sqlite3/lib/sqlite3.js:16:21)
```

It puts data correctly (as I see), but crashes on fetch.

**Comment by domasx2** [comment]
looks like sequelize generates invalid sql for sqlite in this case. Then technically it's a sequelize problem, not sequelize-fixtures

**Comment by zxqfox** [comment]
Looks like ;-( Need to file issue there. I don't have much info about the problem. Seems like as well as you are? ;-D

**Comment by zxqfox** [comment]
As a workaround: We can declare `keys` (https://github.com/domasx2/sequelize-fixtures#detect-duplicates-based-on-select-fields) explicitly to prevent filtering on json fields.

**Comment by scandox** [comment]
+1 for this workaround.

**Comment by php-workx** [comment]
could you please support `sequelize-json` ( https://github.com/Growmies/sequelize-json ) or in general provide a better support for plugins which add hooks to the model instances?

**Comment by domasx2** [comment]
set() is now supported with https://github.com/domasx2/sequelize-fixtures/commit/844fc5ecc93a774c7b10ebf5a96b807e4aa546c5, sequelize-json shouldwork
