### ISSUE TITLE
findById not found on model instances

### ISSUE THREAD

**Issue by ameensol** [domasx2/sequelize-fixtures#38]
Hello, great work on this lib. It's saved me a great deal of time!

Today I noticed that I was getting an error deep in ``loader.js``. The error was:
```
Unhandled rejection TypeError: Object [object SequelizeModel] has no method 'findById'
    at /home/ameen/Desktop/filter/overlord/node_modules/sequelize-fixtures/lib/loader.js:127:100
```

My sequelize version is 2.1.3, and from isolated testing it seems that models no longer have a ``findById`` method. Unfortunately this breaks ``sequelize-fixtures``.

**Comment by ameensol** [comment]
Wrote a pull-request https://github.com/domasx2/sequelize-fixtures/pull/39

**Comment by domasx2** [comment]
Thamks, I'll look into this. Have to see if there's a way to set up tests for older versions too..

**Comment by domasx2** [comment]
btw, models don't have 'findById' for you because your sequelize version is too old, not too new. Updating sequelize to latest version would fix this for you

**Comment by domasx2** [comment]
merged https://github.com/domasx2/sequelize-fixtures/pull/40
