### ISSUE TITLE
question: Is this recommended to feed DB with some initial data?

### ISSUE THREAD

**Issue by diosney** [domasx2/sequelize-fixtures#41]
As title says.

**Comment by domasx2** [comment]
Sure, why not

**Comment by diosney** [comment]
For instance, how this relate to migrations? Do you recommend using this module over inserting the initial data with migrations? Or do  you recommended it only for testing and development purposes?

My main concern is regarding initial data that can change after the initial deployment, for instance, if the primary keys change.

Thanks

**Comment by domasx2** [comment]
This is a utility that makes it easier to prepare some data and insert it. It is not mutually exclusive with sequelize migrations mechanism, which primarly deals with modifying db schema, not data. 
You can use sequelize-fixtures inside a migration to insert initial data. Or you can just prepare a separate script or grunt/gulp task that inserts the data and run it manually on first deployment.

I don't understand the problem with data changing after initial deployment. Normally you would only insert initial data once, during initial deployment, and it wouldn't matter how the data gets modified in the database later.

**Comment by diosney** [comment]
OK, thanks!
