### ISSUE TITLE
Why not to use bulkCreate?

### ISSUE THREAD

**Issue by zxqfox** [domasx2/sequelize-fixtures#43]
Just notices that fixtures doesn't use bulkCreate.

Is it hard or there is another problem?

**Comment by domasx2** [comment]
Currently entities are loaded in sequence as defined in the fixture  files to make sure that related entities are loaded first and relationships setup correctly. That would be harder to do if using bulk create I think

**Comment by zxqfox** [comment]
Only if there are structures like trees or graphs. You can't insert entities into few tables in a step. As I can see it: we can just squash sequential entities for the same model into a pack and if model changed — push the pack into db with bulkCreate. Not so harder. Thoughts?

**Comment by domasx2** [comment]
Could work I guess :) The whole thing could use a rewrite actually, has become messy with many updates and features. But unfortunately I don't use this for any current projects at the time, so have low motivation to do it

**Comment by matmar10** [comment]
Closing this since old and nothing actionable/required here.
