### ISSUE TITLE
jsonb datatype error

### ISSUE THREAD

**Issue by captainill** [domasx2/sequelize-fixtures#45]
I'm not sure of the support for jsonb because it doesn't look to be mentioned or in any tests. Can anyone comment or provide an example?

I'm trying to use

```
  {
    model: 'Post',
    keys: [ 'content'],
    data: {
      id: 0,
      title: 'Test Title 1',
      slug: 'slug-1',
      content: [
        {
          'type': 'text',
          'body': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vulputate ornare elit sed tristique. Cras semper ornare elit, sit amet aliquet odio viverra vel. Sed ultricies nec ante eu tempus. Quisque nec porta nisl.'
        }
      ],
      Tags: [122, 123],
      User: 2
    }
  }
```

I'm getting `Unhandled rejection TypeError: undefined is not a function`. I'm new to using sequelize and sequelize-fixtures tho.

**Comment by domasx2** [comment]
Hi, yeah, haven't really tested this :) try providing content as a string maybe?

**Comment by captainill** [comment]
Hiya, providing the content as a string works but then I get a string out which isn't desired since it adds the extra step of needing to be parsed as opposed to returning a javascript object.

**Comment by domasx2** [comment]
I've added a small fix for jsonb and tested today, works fine (postgres only, of course)
