### ISSUE TITLE
How to set data on a join table embodying an N:M relationship?

### ISSUE THREAD

**Issue by moxious** [domasx2/sequelize-fixtures#46]
In sequelize it's possible to define an n:m relationship, but then define properties on that relationship with a third model [seen here](http://docs.sequelizejs.com/en/latest/api/associations/belongs-to-many/).

I have a setup like that; I'm using `sequelize-fixtures` to load data into both sides of the relationship, but I don't see in the docs how to put data **on** the relationship.   In the sequelize example, they use this:

```
UserProject = sequelize.define('user_project', {
  role: Sequelize.STRING
});
User.belongsToMany(Project, { through: UserProject });
Project.belongsToMany(User, { through: UserProject });
// through is required!

user.addProject(project, { role: 'manager', transaction: t });
```

In JSON fixture data, what I tried (but failed at) was something like this.   This was an (intuitive to me) guess at how it'd be done, but really I can't find anything in the docs on how it should be done.

```
{
   'model': 'User',
   'data': { 'name': 'Bob' }
},
{
  'model': 'Project',
  'data': { 
     'name': 'S00per secret',
     'data': {
         'role': 'manager'
     }
}
```

But no dice on that.

I've also experimented with adding entries for the join table (`UserProject`) but this seems not to work because of the way the models are defined.  From the join table's perspective, it doesn't have relationships to lookup the right User.  And if you define those relationships on the join table so they'll be there, you get a cyclical dependency error from sequelize.

The sequelize docs state that the above setup is the right way to model N:M relationships with properties on the relationship.  So how can I  use `sequelize-fixtures` to get that data in?

**Comment by domasx2** [comment]
Hi, 
I'm afraid sequelize-fixtures does not currently support setting data on a through table for N:M. A pull request is welcome though

**Comment by moxious** [comment]
I'll consider diving into the code and giving it a go.  There seem to be some gotchas I've read about how to load this data even when you're using the pure JS api for sequelize, but it seems basically doable.

Any general guidance on what syntax in the fixtures files would be reasonable to use to trigger this behavior?  Is my example above (with the doubly-nested "data") in the territory of reasonable?

**Comment by domasx2** [comment]
I think there's an error in your example, settings m2m entries is done via plural of the related entity. So for a Project instance you'll want to set it's user list by providing a 'users' data property.

For setting extra data on the rel table my first thought is to add a special 'rel_data' property, like so:

```json
{
   'model': 'User',
   'data': { 'name': 'Bob' }
},
{
  'model': 'Project',
  'data': { 
     'name': 'S00per secret',
     'users': [
          {
                'name': 'Bob',
                'rel_data': {
                    'role': 'Manager'
               }
          }
     ]
}
```
