### ISSUE TITLE
Seed join tables with additional attributes?

### ISSUE THREAD

**Issue by Ltty** [domasx2/sequelize-fixtures#49]
How do you actually seed join tables with additional attributes? 

Please see http://stackoverflow.com/questions/35356987/how-to-handle-additional-attributes-in-join-tables-with-sequelize-fixtures for a detailed description 

Thanks,
Florian

**Comment by domasx2** [comment]
Hi, 
Unfortunately this isn't implemented in sequelize-fixtures. A pull request is welcome though!

**Comment by Ltty** [comment]
Hi,
it took me some time to implement, but I created a pull request that can handle additional attributes for many 2 many relations. Would be happy to see the changes published so I can use it through npm.

**Comment by domasx2** [comment]
now implemented
