### ISSUE TITLE
Fail loading JSONB with array property

### ISSUE THREAD

**Issue by MugeSo** [domasx2/sequelize-fixtures#51]
```javascript
var Model = sequelize.define('something', {
    jsonbField: {
        type: Sequelize.JSONB,
        allowNull: false
    }
});

sequelizeFixtures.loadFixture({
    model: 'something',
    data: {
        jsonbField: {
            prop: [111, 333]
        }
    }
}, {something: Model});
```

Then got
```
Unhandled rejection SequelizeDatabaseError: operator does not exist: text = text[]
```

See also https://github.com/sequelize/sequelize/issues/5582

**Comment by MugeSo** [comment]
Maybe, this can be fixed by https://github.com/meetearnest/sequelize-fixtures/commit/d6cf0ca14210a9da4d7e98a1115c509c65179258

**Comment by domasx2** [comment]
which sequelize version are you on?

**Comment by MugeSo** [comment]
3.19.3

**Comment by domasx2** [comment]
Added a workaround with https://github.com/domasx2/sequelize-fixtures/issues/51

This is really a sequelize issue though...

**Comment by MugeSo** [comment]
@domasx2  thanks a lot!
