### ISSUE TITLE
Why does the fixture loading change the database the foreign keys "on delete" setting? 

### ISSUE THREAD

**Issue by arnaudbesnier** [domasx2/sequelize-fixtures#55]
My freshly created test database contains on delete "CASCADE" option for all the foreign keys.

As soon as I populate the database with my fixtures using sequelize-fixtures, I observe that some foreign keys change their on delete "CASCADE" to on delete "Set NULL".
It creates issues for my tests because this is not the perfect copy of my dev/staging/production database configuration.

It really occurs when I seed the fixtures. No doubt about that.
Do I have to specify options in the models?

Thanks for your help!

**Comment by arnaudbesnier** [comment]
For some foreign keys, adding 
`Model1.hasMany(models.model2, { onDelete: 'cascade' })` in the definition of the model fixes the issue, but sometimes it doesn't...

**Comment by domasx2** [comment]
Hey,

Sequelize-fixtures does not alter schema, something else is going on with your setup. Perhaps you're calling sequelize.sync() somewhere?

Try logging sql queries and see what's going on

**Comment by arnaudbesnier** [comment]
Yes you're right, that was because of a `sequelize.sync()`...
Thank you! (and sorry for the stupid question)
