### ISSUE TITLE
Old glob version is causing a deprecated warning

### ISSUE THREAD

**Issue by jblaketc** [domasx2/sequelize-fixtures#59]
I just ran into this today so I think it just started happening. The glob version used in this project is using minimatch 0.3.0 which I guess has a huge flaw in it so they're throwing a deprecated warning to tell people to upgrade to minimatch 3.0.0 or higher. 

Looks like newest glob is using the appropriate version of minimatch, so if you upgrade the glob dependency version in this project, it should fix the issue.

**Comment by domasx2** [comment]
Thanks, ill look into it
