### ISSUE TITLE
Create tables by default

### ISSUE THREAD

**Issue by krzkaczor** [domasx2/sequelize-fixtures#64]
Hey,
I run into `Unhandled rejection SequelizeDatabaseError: relation "x" does not exist` exception.  The problem was that table with data wasn't created at all.

It would be nice if `sequlize-fixure` could check it and do something like `models.sequelize.sync()` when necessary.

**Comment by domasx2** [comment]
Hi, I think this is out of scope for this lib and would be unexpected. It's easy to manually call sync() if you have to
