### ISSUE TITLE
Request: how can i loadFixtures without running hooks

### ISSUE THREAD

**Issue by julestruong** [domasx2/sequelize-fixtures#67]

**Comment by domasx2** [comment]
Hey,

I don't know, don't see in sequelize docs any way to disable hooks..

**Comment by yktv4** [comment]
@julestruong @domasx2 sequelize has `hooks: false` option available for calls like `.save`, `.create`, etc. you can easily pass this option if you specify `saveOptions` property in your fixture. like that:

```
{
    model: 'Vehicle',
    saveOptions: { hooks: false },
    data: {
        id: 1,
        make: 'BMW',
        model: '5er',
    },
}
```

You can also pass any `buildOptions` same way to use them in a `.build` call.

**Comment by matmar10** [comment]
Answered by @yktv4 

@julestruong I have opened #100 which also disables use of setters, if that's what you need. I think between the two your issue should be solved.
