### ISSUE TITLE
loadFixtures with JSON column types not JSONB 

### ISSUE THREAD

**Issue by pater24** [domasx2/sequelize-fixtures#68]
https://github.com/domasx2/sequelize-fixtures/blob/master/lib/loader.js#L76

> Unhandled rejection SequelizeDatabaseError: operator does not exist: text = text[]

> Unhandled rejection SequelizeDatabaseError: operator does not exist: json = unknown

Is there a way to not use these columns in the where object? Or is there a better way to use regular json columns?

**Comment by probil** [comment]
It seems like `DataTypes.JSON` is not supported at all

**Comment by lukas1994** [comment]
has anyone found a solution?

**Comment by probil** [comment]
@lukas1994 I've changed data type to `JSONB`

**Comment by matmar10** [comment]
I think this has been added. I noticed this line from loader.js 

```javascript
                } else if (fieldType === 'JSON') {
                    where[k] = JSON.stringify(data[k]);
```

Closing as I believe this is now supported. Please reopen if still an issue.

**Comment by m-mitchell** [comment]
I still get this error on `0.10.0`. Switching the data type to `JSONB` fixed the issue.

**Comment by villasv** [comment]
Still getting `Unhandled rejection SequelizeDatabaseError: operator does not exist: json = unknown`  on 1.2

**Comment by robinv85** [comment]
Same issue here, with Postgres JSON type ```SequelizeDatabaseError: operator does not exist: json = unknown```
