### ISSUE TITLE
sequence tables are not updated when manually setting autoincrement ids

### ISSUE THREAD

**Issue by justin-calleja** [domasx2/sequelize-fixtures#71]
It seems like manually setting columns which are autoincremented by db results in the db not updating any sequences it uses to track autoincrementing.

The result of this is that, if you now try to create any test data leaving 'DEFAULT' (empty) for autoincremented fields like PKs, an exception will be thrown if you manually created id 1 and db's sequence is at 0 incrementing by 1 (as it will try to insert two 1s for PK id).

You might want to do this while testing e.g. populate db in known state for all find operations - then create your own entries in the db for create, update, delete operations - leaving the db in <on-loaded-fixtures-state> after every test.

Please make a note of this in the README.md.

Thank you

**Comment by justin-calleja** [comment]
tmp work-around:

```
await db.sequelize.query(
    `ALTER SEQUENCE "ItemInstances_id_seq" RESTART WITH ${itemInstances.length + 1};`
);
```

**Comment by didnotwant** [comment]
Exactly the same problem here. @justin-calleja – did you find any better solution for that?

**Comment by justin-calleja** [comment]
@didnotwant , I reverted back to inserting the fixture data "by hand" without using sequelize-fixtures.

Had started a project to get around this but stopped developing it. The idea was to create a [dependency graph](https://en.wikipedia.org/wiki/Dependency_graph) (directed acyclic graph) out of fixture data, traverse graph with [toposort](https://github.com/marcelklehr/toposort) such that you always go dependency first (e.g. a table whose id the db will generate) - that way you create all necessary rows and get back db auto increments before creating all dependent rows.

In any case, I'll comment back here if I ever get round to publishing it on npm.

**Comment by rostislavprovodenko** [comment]
@justin-calleja do you know why sequelize-fixtures does this? I don't see anywhere in its code where it'd change sequelize or the database settings

**Comment by justin-calleja** [comment]
@rostislavprovodenko I'm not sure I understand what you're asking. sequelize-fixtures just inserts the data *as is*. If that data is meant to be auto-incremented by db... there will be problems as the db doesn't know sequelize-fixtures is inserting those.

Turns out we need the auto incremented values when writing fixture data with dependencies on these auto generated values... so .. basically this requirement makes sequelize-fixtures un-workable in my experience... maybe I'm missing something.

Re the project I had in mind and mentioned in a previous comment... turns out just inserting the data yourself is easier (i.e. use whatever you use in your app to populate the db for generating your test fixtures).

**Comment by matmar10** [comment]
Closing this as it's old. If still needed and you have a proposed change in behavior, please reopen and comment.
