### ISSUE TITLE
v4 incompatabiliy - Error: models.User appears to be a function

### ISSUE THREAD

**Issue by georgeedwards** [domasx2/sequelize-fixtures#79]
I have just upgraded to v4. I am now getting the issue:

> Unhandled rejection Error: models.User appears to be a function. Perhaps you are importing model factory function? You should then use sequelize.import to create your model, see https://github.com/sequelize/express-example/blob/master/models/index.js#L17

Here is an example of the **seed.json** file I am using:

```
[{
        "model": "User",
        "data": {
            "email": "test@test.com",
            "password": "Password",
            "role": "Operator"
        }
}]
```

here is my User model:

```
export default function defineUser(sequelize: Sequelize.Sequelize, DataTypes) {
  var User = sequelize.define<UserInstance, UserAttributes>('User', {
    email: {
      type: Sequelize.STRING,
      unique: true,
      validate: { isEmail: true }
    },
    password: Sequelize.STRING,
    role: {
      type: DataTypes.ENUM,
      values: ['Admin', 'Operator', 'Member']
    }
  });

  User.beforeCreate(function (user: UserInstance, options) {
    return hashPassword(user.password).then(function (hashedPw) {
      user.password = hashedPw;
    });
  })
  return User;
};
```
I haven't got much further with my debugging, but it is definitely the test-fixture causing the issue. Aside from that, sequelize seems to be working fine with the model definition.

**Comment by matmar10** [comment]
I believe this is fixed. I am currently using with v4 without issues. Please reopen if still an issue.
