### ISSUE TITLE
Proposed fix: Fix `through` associations on join tables

### ISSUE THREAD

**Issue by pcsanwald** [domasx2/sequelize-fixtures#83]
The current problem with adding attributes to join tables is due to the following change in sequelize:

v3:
`group.addUser( alice, { role: 'member' });`

v4:
`group.addUser( alice, { through: { role: 'member' }});`

I've forked the repo, upgraded sequelize, made the required fix. I'm happy to open a PR for this repo, if you are ok with dropping support for sequelize v3. Thoughts?

**Comment by sevarubbo** [comment]
Please do!

**Comment by seahyc** [comment]
Yup, would appreciate it greatly!

**Comment by hugodes** [comment]
Yes, we're left hanging on our update to v4, please submit a PR.
@pcsanwald could you provide a link to your fork so we can use it on our project in the meantime ?
cheers

**Comment by pcsanwald** [comment]
Sorry everyone, will submit a PR in a couple hours

Best,

--paul

**Comment by pcsanwald** [comment]
@sevarubbo @hugodes @seahyc this is addressed in PR #84

**Comment by hugodes** [comment]
@domasx2 could you release this with a version bump please ?

**Comment by domasx2** [comment]
Done, 0.7.0
