### ISSUE TITLE
Duplicate records being inserted

### ISSUE THREAD

**Issue by Kallaste** [domasx2/sequelize-fixtures#86]
Hello,

I was under the impression from the docs that duplicates would not be inserted, however, I have a database with identical records being created on each program run. Calling very simply with:

```
if(app.get('env') === 'development'){
    sequelize_fixtures.loadFile('fixtures/*.json', db);
  }
```
I'm a C/Java programmer and I'm not very familiar with Node.js or JavaScript, so maybe I am missing something? Sorry if that is the case.

**Comment by matmar10** [comment]
Hi @Kallaste - you may need to specify a field to indentify the duplicates. Please see the docs under "Detect duplicates based on select fields". you need to specify the `keys` field:

On the first will be inserted in the following example:

```json
{
    "model": "Person",
    "keys": ["email"],
    "data": {
        "name": "John",
        "email": "example@example.com"
    }
},
{
    "model": "Person",
    "keys": ["email"],
    "data": {
        "name": "Patrick",
        "email": "example@example.com"
    }
}
```
