### ISSUE TITLE
sequelize deprecated Model.find has been deprecated, please use Model.findOne instead at

### ISSUE THREAD

**Issue by funtom48** [domasx2/sequelize-fixtures#92]
Hello.
sequelize version: "4.41.0"

method find has been deprecated. We need to use the "findOne" or "findByPk" methods

**Comment by modestfake** [comment]
@domasx2 I've created a PR to address this issue here #97

**Comment by modestfake** [comment]
Sequelize v5 is [released](https://github.com/sequelize/sequelize/releases/tag/v5.1.0). This issue is a blocker for those who want to migrate to a new version of Sequelize. @domasx2 are you able to review a PR #97?

**Comment by modestfake** [comment]
@domasx2 Thank you!

**Comment by domasx2** [comment]
hey, sorry about the lack of attention... released 0.9.1 to npm

**Comment by modestfake** [comment]
No worries, I know you're not supporting it anymore, so any attention to is much appreciated by the community! 👍
