### ISSUE TITLE
NEW MAINTAINER WANTED

### ISSUE THREAD

**Issue by matmar10** [domasx2/sequelize-fixtures#98]
Alas, as @domasx2  has noted:

> I'm no longer using Sequelize or this lib, and have very little motivation to maintain it. If someone wants to take over, let me know!

Raising this issue to start a thread for possible maintainers. My organization relies on this heavily, so I'm willing to throw my hat in the ring.

Any other volunteers / candidates?

**Comment by yjwong** [comment]
My company also relies on this library heavily, would be willing to help co-maintain this library.

**Comment by zazoomauro** [comment]
Any update on this? I'm also interested. I'm using it quite often

**Comment by matmar10** [comment]
@domasx2 can you chime in? We have some hats thrown in the ring, here.

**Comment by domasx2** [comment]
Hey, added @matmar10  as collaborator because he has multiple PRs open :) However, please try to required unit tests for features whenever possible. Please email me npm username, will add as npm maintainer too, so you can publish new releases

**Comment by matmar10** [comment]
Thanks, @domasx2 for the quick reply to my request. Noted with thanks - now that I'm certain we'll be able to cut releases, I'm happy to invest some time adding unit test for features and such.

My npm username is the same: matmar10

**Comment by domasx2** [comment]
@matmar10 added to npm maintainers as well. Thank you for picking this up :)
